import "@/styles/globals.scss";
import { SessionProvider } from "next-auth/react";
import Navbar from "./components/Navbar";
import styles from "@/styles/layout.module.scss";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const nav = <Navbar />;
    return (
        <html lang="en">
            <SessionProvider>
                <body>
                    {nav}
                    <div className={styles["container-nav"]}>{children}</div>
                </body>
            </SessionProvider>
        </html>
    );
}
